
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-09T16:59:37+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b151fbc19c16da983e6d1ee83ecbb8e8f6356ba5",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
