# Generated by Django 4.1.7 on 2023-03-07 11:11

import django.core.validators
from django.db import migrations, models
import wagtail.blocks.stream_block
import wagtail_block_model_field.fields
import wagtail_preference_blocks.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='', max_length=128, validators=[django.core.validators.RegexValidator('^[A-Za-z_][A-Za-z_0-9]*$', code='invalid_identifier', message='A valid identifier starts with an alphanumeric letter or underscore and contains only alphanumeric letters, underscores or digits.')])),
                ('description', models.CharField(default='', max_length=255)),
                ('preferences', wagtail_block_model_field.fields.BlockModelField(wagtail_preference_blocks.blocks.PreferencesBlock(), wagtail.blocks.stream_block.StreamValue)),
            ],
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('identifier',), name='unique_wagtail_preference_blocks_profile.identifier'),
        ),
    ]
