
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-09T19:04:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c724f37e476b6bbe55323cf1cabec95125f04a7",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
