from setuptools import setup
setup(
    name='weatherpy2',
    packages=['jetbrainsfleetrun'],
    version="1.0.0",
    liscense="MIT",
    description="Easy Python file running in JetBrains Fleet",
    author="GamerXZEN",
    author_email="codspecialops@gmail.com",
    url="https://github.com/GamerXZEN/jetbrainsfleetrun",
    keywords=["weather", "forecast", "python",],
    install_requires=["requests"],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Build Tools",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
)