
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9ba981a2ea789030927fc49b6ad166bc68f6b5f9",
 "version": "1.9.0rc6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
