from typing import Any, List, Tuple

class Mapping:
    def __init__(self, teacher: Module, student: Module) -> None: ...
    def add(self, teacher_module: Mappable, student_module: Mappable, payload: Any = ...) -> None: ...
    def apply(self) -> Tuple[Module, Module]: ...
    def revert(self) -> Tuple[Module, Module]: ...
    @property
    def teacher(self) -> Module: ...
    @property
    def student(self) -> Module: ...
    def payload(self) -> List[Any]: ...
