VERSION_YEAR = 2023
VERSION_MONTH = int('05')
VERSION_DAY = int('07')
VERSION_HOUR = int('03')
VERSION_MINUTE = int('59')
MAJOR_VERSION = 1
MINOR_VERSION = 4
PATCH_VERSION = 202305070359
version_date = '2023/05/07 03:59'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
