# This file automatically generated by
#    /Users/couchbase/jenkins/workspace/python/sdk/python-scripted-build-pipeline/py-client/./couchbase_version.py
# at
#    2023-05-09 12:15:58.679562
__version__ = '4.1.4'