# coding: utf-8

"""
    Synctera API

    <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>  # noqa: E501

    The version of the OpenAPI document: 0.49.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from synctera_client import schemas  # noqa: F401


class ProvisioningControls(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def in_app_provisioning() -> typing.Type['InAppProvisioning']:
                return InAppProvisioning
        
            @staticmethod
            def manual_entry() -> typing.Type['ManualEntry']:
                return ManualEntry
        
            @staticmethod
            def wallet_provider_card_on_file() -> typing.Type['WalletProviderCardOnFile']:
                return WalletProviderCardOnFile
            __annotations__ = {
                "in_app_provisioning": in_app_provisioning,
                "manual_entry": manual_entry,
                "wallet_provider_card_on_file": wallet_provider_card_on_file,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["in_app_provisioning"]) -> 'InAppProvisioning': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["manual_entry"]) -> 'ManualEntry': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["wallet_provider_card_on_file"]) -> 'WalletProviderCardOnFile': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["in_app_provisioning", "manual_entry", "wallet_provider_card_on_file", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["in_app_provisioning"]) -> typing.Union['InAppProvisioning', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["manual_entry"]) -> typing.Union['ManualEntry', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["wallet_provider_card_on_file"]) -> typing.Union['WalletProviderCardOnFile', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["in_app_provisioning", "manual_entry", "wallet_provider_card_on_file", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        in_app_provisioning: typing.Union['InAppProvisioning', schemas.Unset] = schemas.unset,
        manual_entry: typing.Union['ManualEntry', schemas.Unset] = schemas.unset,
        wallet_provider_card_on_file: typing.Union['WalletProviderCardOnFile', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ProvisioningControls':
        return super().__new__(
            cls,
            *_args,
            in_app_provisioning=in_app_provisioning,
            manual_entry=manual_entry,
            wallet_provider_card_on_file=wallet_provider_card_on_file,
            _configuration=_configuration,
            **kwargs,
        )

from synctera_client.model.in_app_provisioning import InAppProvisioning
from synctera_client.model.manual_entry import ManualEntry
from synctera_client.model.wallet_provider_card_on_file import WalletProviderCardOnFile
