from typing import Any

class RunningMeanLogger:
    def __init__(self, momentum: float = ...) -> None: ...
    @property
    def running_value(self) -> Any: ...
    @running_value.setter
    def running_value(self, value: Any) -> None: ...
