
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-09T09:24:42-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b40245e3d83acd409c0041b6e12dca2fb565c74a",
 "version": "0.29.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
