# Generated by Django 4.2 on 2023-05-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("skill_score", models.FloatField(null=True)),
                ("state", models.CharField(max_length=8, null=True)),
                ("answer", models.IntegerField(null=True)),
            ],
        ),
    ]
