

CITATION_FEATURE_NAME = 'concisely.citation'
CITATION_ENTITY_TYPE = 'concisely.CITATION'

QUOTATION_FEATURE_NAME = 'concisely.quotation'
QUOTATION_ENTITY_TYPE = 'concisely.QUOTATION'

EMPHASIS_FEATURE_NAME = 'concisely.emphasis'
EMPHASIS_ENTITY_TYPE = 'concisely.EMPHASIS'

ATTENTION_FEATURE_NAME = 'concisely.attention'
ATTENTION_ENTITY_TYPE = 'concisely.ATTENTION'

IMPORTANCE_FEATURE_NAME = 'concisely.importance'
IMPORTANCE_ENTITY_TYPE = 'concisely.IMPORTANCE'

DEFINITION_FEATURE_NAME = 'concisely.definition'
DEFINITION_ENTITY_TYPE = 'concisely.DEFINITION'

ALTERNATION_FEATURE_NAME = 'concisely.alternation'
ALTERNATION_ENTITY_TYPE = 'concisely.ALTERNATION'

SMALL_FEATURE_NAME = 'concisely.small'
SMALL_ENTITY_TYPE = 'concisely.SMALL'

ABBREVIATION_FEATURE_NAME = 'concisely.abbreviation'
ABBREVIATION_ENTITY_TYPE = 'concisely.ABBREVIATION'

USER_INPUT_FEATURE_NAME = 'concisely.input'
USER_INPUT_ENTITY_TYPE = 'concisely.INPUT'

SYSTEM_OUTPUT_FEATURE_NAME = 'concisely.output'
SYSTEM_OUTPUT_ENTITY_TYPE = 'concisely.OUTPUT'

CODE_FEATURE_NAME = 'concisely.code'
CODE_ENTITY_TYPE = 'concisely.CODE'

VARIABLE_FEATURE_NAME = 'concisely.variable'
VARIABLE_ENTITY_TYPE = 'concisely.VARIABLE'

SUBSCRIPT_FEATURE_NAME = 'concisely.subscript'
SUBSCRIPT_ENTITY_TYPE = 'concisely.SUBSCRIPT'

SUPERSCRIPT_FEATURE_NAME = 'concisely.superscript'
SUPERSCRIPT_ENTITY_TYPE = 'concisely.SUPERSCRIPT'

DELETION_FEATURE_NAME = 'concisely.deletion'
DELETION_ENTITY_TYPE = 'concisely.DELETION'

INSERTION_FEATURE_NAME = 'concisely.insertion'
INSERTION_ENTITY_TYPE = 'concisely.INSERTION'

BLOCKQUOTE_FEATURE_NAME = 'concisely.blockquote'
BLOCKQUOTE_ENTITY_TYPE = 'concisely.BLOCKQUOTE'

PREFORMATTED_FEATURE_NAME = 'concisely.preformatted'
PREFORMATTED_ENTITY_TYPE = 'concisely.PREFORMATTED'

HEADING_FEATURE_NAME = 'concisely.heading'
HEADING_ENTITY_TYPE = 'concisely.HEADING'


feature_names = [
    CITATION_FEATURE_NAME,

    QUOTATION_FEATURE_NAME,
    EMPHASIS_FEATURE_NAME,

    ATTENTION_FEATURE_NAME,

    IMPORTANCE_FEATURE_NAME,

    DEFINITION_FEATURE_NAME,

    ALTERNATION_FEATURE_NAME,

    SMALL_FEATURE_NAME,

    ABBREVIATION_FEATURE_NAME,

    USER_INPUT_FEATURE_NAME,

    SYSTEM_OUTPUT_FEATURE_NAME,

    CODE_FEATURE_NAME,

    VARIABLE_FEATURE_NAME,

    SUBSCRIPT_FEATURE_NAME,

    SUPERSCRIPT_FEATURE_NAME,

    DELETION_FEATURE_NAME,

    INSERTION_FEATURE_NAME,

    BLOCKQUOTE_FEATURE_NAME,

    PREFORMATTED_FEATURE_NAME,

    HEADING_FEATURE_NAME
]
