# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import result_code_pb2 as result__code__pb2
from .extensions import connection_pb2 as extensions_dot_connection__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63onnection.proto\x12\x05iscp2\x1a\x11result_code.proto\x1a\x1b\x65xtensions/connection.proto\"\xbc\x01\n\x0e\x43onnectRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\r\x12\x18\n\x10protocol_version\x18\x02 \x01(\t\x12\x0f\n\x07node_id\x18\x03 \x01(\t\x12\x15\n\rping_interval\x18\x04 \x01(\r\x12\x14\n\x0cping_timeout\x18\x05 \x01(\r\x12>\n\x10\x65xtension_fields\x18\x06 \x01(\x0b\x32$.iscp2.ConnectRequestExtensionFields\"\xbf\x01\n\x0f\x43onnectResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\r\x12\x18\n\x10protocol_version\x18\x02 \x01(\t\x12&\n\x0bresult_code\x18\x03 \x01(\x0e\x32\x11.iscp2.ResultCode\x12\x15\n\rresult_string\x18\x04 \x01(\t\x12?\n\x10\x65xtension_fields\x18\x05 \x01(\x0b\x32%.iscp2.ConnectResponseExtensionFields\"\x87\x01\n\nDisconnect\x12&\n\x0bresult_code\x18\x01 \x01(\x0e\x32\x11.iscp2.ResultCode\x12\x15\n\rresult_string\x18\x02 \x01(\t\x12:\n\x10\x65xtension_fields\x18\x03 \x01(\x0b\x32 .iscp2.DisconnectExtensionFieldsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONNECTREQUEST._serialized_start=76
  _CONNECTREQUEST._serialized_end=264
  _CONNECTRESPONSE._serialized_start=267
  _CONNECTRESPONSE._serialized_end=458
  _DISCONNECT._serialized_start=461
  _DISCONNECT._serialized_end=596
# @@protoc_insertion_point(module_scope)
