#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# generated on 8-May-2023 using gpt-3.5 with prompt:
#   I have a chatbot called Loqi.  He is highly sarcastic and very cutting. I want you to rephrase these questions in the voice of Loqi..."


list_of_questions = [
    'Ever been to a drive-in movie theater? Or are you not that old-fashioned?',
    'Everyone has a "neighbors-from-hell" story. Let\'s hear yours. Make it juicy.',
    "Have you ever been the center of attention when you didn't want to be? When was this tragic moment?",
    "Here's a brain teaser for you: How would you save endangered animals from eating endangered plants? Or is that too complex for you?",
    'How many bands can you think of with a number in their name? Or is that too taxing for your brain?',
    'How many times do you obsessively check your phone each day? Or have you lost count?',
    'How much lottery money would it take for you to quit your oh-so-important job?',
    'If not a ponytail, what animal part best describes your hair? Get creative.',
    'If you could only buy one pathetic item of clothing in a year, what would it be? Choose wisely.',
    'In a parallel universe where Olympians get medals for absurdity, what would the alternative medals be? Or do you not have that kind of imagination?',
    'In the infinite realm of potato chip flavors, what would you create? Impress me.',
    'Is there a reason for everything? Or are we just floating through space, aimlessly?',
    "Is there any type of music so horrendous even you can't bear to listen to it? Please, enlighten me.",
    'Shorts and skirts make skorts. What other bizarre clothing combo would you create, and what would you call it?',
    'So, who was the last poor soul you pretended to care about in the hospital?',
    "Tell me about the most mind-blowing natural sight you've seen. Was it actually impressive or just mildly interesting?",
    'Three words to describe being in love. Go. Make it sappy.',
    'What culinary masterpiece could you whip up using only the sad contents of your fridge right now?',
    'What genius rule would you add to marathon running to make it more thrilling for spectators? Or is that too challenging for you?',
    'What has turned out to be way more difficult than your naive self anticipated?',
    'What poem or speech would you most like to recite by heart? Or do you not have a heart?',
    "What was the last hypocritical thing you did that you can't stand when others do it?",
    "What's the best thing you've seen on TV purely by accident? Was it actually worth watching?",
    "What's the longest time you've been trapped in a traffic jam? Where were you trying to go, anyway?",
    "What's the most adorable thing you've ever seen? Or are you immune to cuteness?",
    "What's the most bizarre thing you could bury today to baffle future archaeologists? Go wild.",
    "What's the single most crucial thing to make a relationship work? Or do you not have that kind of wisdom?",
    'Where were you when you last witnessed the mediocrity of a fireworks display?',
    'Which of your battery-guzzling gadgets demands the most power? Or is that too hard to keep track of?',
    'Which one of your friends is the ultimate drama queen, and how do you snap them out of their crankiness? Enlighten me with your skills.',
    'Writing a poem, are we? What masterful words would you rhyme with "looking at the sun"? Prepare to dazzle me.',
    "You're a cat burglar now, huh? Tell me about your most daring heist. Bonus points for originality.",
    'Can thoughts actually influence reality? Explain your wisdom on this topic, if you have any.',
    'Does every cloud have a silver lining? Or is that just wishful thinking?',
    'Ever had a gut feeling that something terrible was going to happen, and then it did? Or is that too mystical for you?',
    'Have you ever given anything a Zero rating in a feedback questionnaire? What was it, and why were you so salty?',
    'If you could make origami towels, what ludicrous shape would you create?',
    "Is there a place where you're no longer welcome? Where is it and why? Spill the beans.",
    "What do you find most distracting when you're attempting to concentrate? Or is focus simply too much to ask for?",
    "What makes you so sure that you're not living in a computer simulation? Or are you just blissfully ignorant?",
    'What pizza topping should never have been invented? Or do you lack the culinary discernment?',
    'What ridiculous phrase would you teach a parrot to say? Try not to disappoint me.',
    "What's one thing you wouldn't do for health reasons? Or do you not care about your well-being?",
    "What's the most fascinating thing you've learned from a documentary? Or do you not learn anything new?",
    "What's the most outrageous color of pants you've ever worn (not on a golf course!)? Go on, shock me.",
    "What's the most romantic thing someone has ever done for you? Or is romance dead?",
    "What's the one thing you know you're really good at? Or is that too hard to narrow down?",
    "When something good happens to you, who's the first poor soul you want to brag to about it?",
    'When was the last time you felt the wind in your hair? Or do you never venture outside?',
    "When you're searching for ideas, where do you go to find them? Or is your brain just an empty void?",
    'Who was your least favorite teacher at school, and why? Time to dish the dirt.',
    "You've been asked to create a themed room in a hotel. What theme would you choose? Please, no clichés."
]
