__built_time__        =  "built at Tue May  9 18:14:10 2023_CST"
__name__              =  "pyasd"
__version__           =  "0.0.6"
__author__            =  "Shunhong Zhang"
__author_email__      =  "zhangshunhong.pku@gmail.com"
__url__               =  "https://to_be_posted"
__license__           =  "LICENSE"
__platform__          =  "linux"
