
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-08T17:40:02+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d952ec081ad2a70619936daa5c7fd8e3302e0f74",
 "version": "1.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
