
OFFICEKIT_GROUP_ASSIGNMENTS_QUERY_FORM_CLASSNAME = ""
OFFICEKIT_GROUP_MEMBERS_QUERY_FORM_CLASSNAME = ""
OFFICEKIT_GROUPS_QUERY_FORM_CLASSNAME = ""

OFFICEKIT_GROUP_ASSIGNMENT_LAYOUT_BLOCK_CLASSNAME = ""
OFFICEKIT_GROUP_ASSIGNMENT_LIST_BLOCK_CLASSNAME = "group-assignment-list"

OFFICEKIT_GROUP_MEMBER_LAYOUT_BLOCK_CLASSNAME = ""
OFFICEKIT_GROUP_MEMBER_LIST_BLOCK_CLASSNAME = "group-member-list"
OFFICEKIT_GROUP_MEMBER_CLASSNAME = "group-member"
OFFICEKIT_GROUP_MEMBER_PERSON_CLASSNAME = "person"
OFFICEKIT_GROUP_MEMBER_ORGANISATION_CLASSNAME = "organisation"

OFFICEKIT_GROUP_LAYOUT_BLOCK_CLASSNAME = ""
OFFICEKIT_GROUP_LIST_BLOCK_CLASSNAME = "group-list"
OFFICEKIT_GROUP_LIST_MEMBER_LAYOUT_BLOCK_CLASSNAME = ""

OFFICEKIT_NAME_LIST_BLOCK_CLASSNAME = "name-list"
OFFICEKIT_NAME_LIST_BLOCK_NAME_CLASSNAME = "name"
OFFICEKIT_NAME_LIST_BLOCK_PERSON_CLASSNAME = "person"
OFFICEKIT_NAME_LIST_BLOCK_ORGANISATION_CLASSNAME = "organisation"
