# Generated by Django 3.2.12 on 2022-04-07 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devind_dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='user',
            field=models.ForeignKey(help_text='Director of department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(help_text='Users in departments.', related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
