# Generated by Django 3.2.16 on 2023-04-05 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devind_dictionaries', '0004_auto_20220421_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(db_constraint=False, default=None, help_text='Parent', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devind_dictionaries.organization'),
        ),
    ]
