# coding: utf-8

"""
    Synctera API

    <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>  # noqa: E501

    The version of the OpenAPI document: 0.49.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from synctera_client import schemas  # noqa: F401


class DocumentType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    The type of the document
    """
    
    @schemas.classproperty
    def APPLICATION_DOCUMENTATION(cls):
        return cls("APPLICATION_DOCUMENTATION")
    
    @schemas.classproperty
    def CHECK_IMAGE(cls):
        return cls("CHECK_IMAGE")
    
    @schemas.classproperty
    def IDENTITY_DOCUMENTATION(cls):
        return cls("IDENTITY_DOCUMENTATION")
    
    @schemas.classproperty
    def STATEMENT_DISCLOSURE(cls):
        return cls("STATEMENT_DISCLOSURE")
    
    @schemas.classproperty
    def TERMS_OF_SERVICE(cls):
        return cls("TERMS_OF_SERVICE")
    
    @schemas.classproperty
    def COMPLIANCE_REPORT(cls):
        return cls("COMPLIANCE_REPORT")
    
    @schemas.classproperty
    def STATEMENT(cls):
        return cls("STATEMENT")
    
    @schemas.classproperty
    def COMPANY_PROFILE_DOCUMENT(cls):
        return cls("COMPANY_PROFILE_DOCUMENT")
    
    @schemas.classproperty
    def FINANCIAL_FILE(cls):
        return cls("FINANCIAL_FILE")
