# coding: utf-8

"""
    Synctera API

    <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>   # noqa: E501

    The version of the OpenAPI document: 0.32.0.dev6
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from synctera_client import schemas  # noqa: F401


class Waitlist(
    schemas.ComposedSchema,
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        
        class all_of_0(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                required = {
                    "waitlist_name",
                    "increment",
                }
                
                class properties:
                    creation_time = schemas.DateTimeSchema
                    id = schemas.UUIDSchema
                    last_updated_time = schemas.DateTimeSchema
                    num_admitted = schemas.IntSchema
                    num_created = schemas.IntSchema
                    num_prospects = schemas.IntSchema
                    num_verified = schemas.IntSchema
                    num_withdrawn = schemas.IntSchema
                    __annotations__ = {
                        "creation_time": creation_time,
                        "id": id,
                        "last_updated_time": last_updated_time,
                        "num_admitted": num_admitted,
                        "num_created": num_created,
                        "num_prospects": num_prospects,
                        "num_verified": num_verified,
                        "num_withdrawn": num_withdrawn,
                    }
            
            waitlist_name: schemas.AnyTypeSchema
            increment: schemas.AnyTypeSchema
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["creation_time"]) -> MetaOapg.properties.creation_time: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["last_updated_time"]) -> MetaOapg.properties.last_updated_time: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["num_admitted"]) -> MetaOapg.properties.num_admitted: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["num_created"]) -> MetaOapg.properties.num_created: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["num_prospects"]) -> MetaOapg.properties.num_prospects: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["num_verified"]) -> MetaOapg.properties.num_verified: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["num_withdrawn"]) -> MetaOapg.properties.num_withdrawn: ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["creation_time", "id", "last_updated_time", "num_admitted", "num_created", "num_prospects", "num_verified", "num_withdrawn", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["creation_time"]) -> typing.Union[MetaOapg.properties.creation_time, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["last_updated_time"]) -> typing.Union[MetaOapg.properties.last_updated_time, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["num_admitted"]) -> typing.Union[MetaOapg.properties.num_admitted, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["num_created"]) -> typing.Union[MetaOapg.properties.num_created, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["num_prospects"]) -> typing.Union[MetaOapg.properties.num_prospects, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["num_verified"]) -> typing.Union[MetaOapg.properties.num_verified, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["num_withdrawn"]) -> typing.Union[MetaOapg.properties.num_withdrawn, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["creation_time", "id", "last_updated_time", "num_admitted", "num_created", "num_prospects", "num_verified", "num_withdrawn", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *_args: typing.Union[dict, frozendict.frozendict, ],
                waitlist_name: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                increment: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                creation_time: typing.Union[MetaOapg.properties.creation_time, str, datetime, schemas.Unset] = schemas.unset,
                id: typing.Union[MetaOapg.properties.id, str, uuid.UUID, schemas.Unset] = schemas.unset,
                last_updated_time: typing.Union[MetaOapg.properties.last_updated_time, str, datetime, schemas.Unset] = schemas.unset,
                num_admitted: typing.Union[MetaOapg.properties.num_admitted, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                num_created: typing.Union[MetaOapg.properties.num_created, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                num_prospects: typing.Union[MetaOapg.properties.num_prospects, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                num_verified: typing.Union[MetaOapg.properties.num_verified, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                num_withdrawn: typing.Union[MetaOapg.properties.num_withdrawn, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_0':
                return super().__new__(
                    cls,
                    *_args,
                    waitlist_name=waitlist_name,
                    increment=increment,
                    creation_time=creation_time,
                    id=id,
                    last_updated_time=last_updated_time,
                    num_admitted=num_admitted,
                    num_created=num_created,
                    num_prospects=num_prospects,
                    num_verified=num_verified,
                    num_withdrawn=num_withdrawn,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                cls.all_of_0,
                WaitlistEditable,
            ]


    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Waitlist':
        return super().__new__(
            cls,
            *_args,
            _configuration=_configuration,
            **kwargs,
        )

from synctera_client.model.waitlist_editable import WaitlistEditable
