
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-28T14:12:55-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "399150242426882aafcce06688a6a9b8e61d0c0d",
 "version": "1.0.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
