# Generated by Django 3.0.14 on 2023-03-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcmr', '0008_auto_20230331_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='nft_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
