
PERMA_RECORD_PAGE_TEMPLATE = "perma/base_page.html"

PERMA_RECORD_BLOCK_CLASSNAME = ""

PERMA_RECORD_BLOCK_AUTHORS_CLASSNAME = "author-list"
PERMA_RECORD_INDEX_REDIRECT_TARGET = ""
PERMA_RECORD_INDEX_NOT_ACCESSIBLE = True

PERMA_RECORD_TAGS_BLOCK_CLASSNAME = "keywords-list"
PERMA_RECORD_TAGS_BLOCK_CONTAINER_ELEMENT = "div"
PERMA_RECORD_TAGS_BLOCK_TAG_CLASSNAME = "tag"
